### ISSUE TITLE
mac osx compatibility / installation?

### ISSUE THREAD

**Issue by dushyant-basson** [Digital-Structures/ghpythonremote#17] opened 2019-02-05 14:08 UTC
What are the installation steps for the Mac OSX environment (if ghpythonremote works there)? Thanks.

**Comment by pilcru** [comment] 2019-02-05 16:30
I've never tried it, but in general you should be able to get it to work on Rhino 6 for Mac. However, you will run into the same kind of installation path issues as in Rhino 6 for Windows (see #9), and you will have to adapt to the folder structure on Mac. Also, things like automatically finding the path to your conda installation might not work since it tries to read Windows registry keys.

In Rhino 5 for Mac, it might be a little harder, given the large differences with the windows version, especially in terms of scripting. Still worth a try though!

If you decide to try this, please write back and tell us what worked or not. You are also welcome to send a pull request that incorporates the changes.

**Comment by dushyant-basson** [comment] 2019-02-06 08:37
I tried installing it like this:
$ sudo pip install gh-python-remote
Password:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
The directory '/Users/onizu-db/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/onizu-db/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting gh-python-remote
  Downloading https://files.pythonhosted.org/packages/87/0d/5e9806e2aae5e1f7bbf879d5d49b08cc155d0d29e32b8da78282018eaba0/gh_python_remote-1.1.4-py2-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 412kB/s 
Collecting rpyc>=3.4.6 (from gh-python-remote)
  Downloading https://files.pythonhosted.org/packages/ba/88/1cea477a4ad7c0f546a4c82aa367185be7b8fce512db8283e82de8454772/rpyc-4.0.2.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 8.1MB/s 
Collecting plumbum (from rpyc>=3.4.6->gh-python-remote)
  Downloading https://files.pythonhosted.org/packages/48/48/0c592a65c8ecc6a4c0da41d75097704a283595b6731be1531eee3f4f7778/plumbum-1.6.7-py2.py3-none-any.whl (110kB)
    100% |████████████████████████████████| 112kB 8.7MB/s 
Installing collected packages: plumbum, rpyc, gh-python-remote
  Running setup.py install for rpyc ... done
Successfully installed gh-python-remote-1.1.4 plumbum-1.6.7 rpyc-4.0.2

--
So it installed. Then I tried the command for configuring ghpythonremote with IronPython using the command mentioned here: https://pypi.org/project/gh-python-remote/
It looked for windows paths by default. I didn't try with a custom location. Below is the log for your reference:

$ python -m ghpythonremote._configure_ironpython_installation
WARNING:No ghpy_version.txt file installation found in McNeel/Rhinoceros/5.0/Plug-ins/IronPython (814d908a-e25c-493d-97e9-ee3861957f49)/settings.
Was ghpython installed and opened in Grasshopper at least once on this machine?
ERROR:IronPython lib directory for Rhinoceros not found in McNeel/Rhinoceros/5.0/Plug-ins/IronPython (814d908a-e25c-493d-97e9-ee3861957f49)/settings.
Please provide a full path to one of the folders in your IronPython for Rhinoceros path.
These folders are listed in the settings of the window opened with the command `_EditPythonScript` in Rhinoceros
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/ghpythonremote/_configure_ironpython_installation.py", line 15, in <module>
    rhino_ironpython_path = get_rhino_ironpython_path(location=location)
  File "/Library/Python/2.7/site-packages/ghpythonremote/helpers.py", line 78, in get_rhino_ironpython_path
    return get_ironpython_from_appdata()
  File "/Library/Python/2.7/site-packages/ghpythonremote/helpers.py", line 121, in get_ironpython_from_appdata
    raise RuntimeError('No IronPython lib folder found in %APPDATA%')
RuntimeError: No IronPython lib folder found in %APPDATA%

-- 
I installed IronPython from the pkg file available here: https://github.com/IronLanguages/ironpython2/releases/tag/ipy-2.7.9

**Comment by opasquetdotfr** [comment] 2020-10-05 14:49
I am also trying to install it on MacOS 10.13.6 for Rhino 6.

- "pip install gh-python-remote --upgrade" runs fine.
Files are in ~/Library/Python/2.7/lib/python/site-packages/ghpythonremote

- I simply replaced the path in "_configure_ironpython_installation.py" for MacOS: "/" instead of "C:\\"

- I installed everything without apparent problem running:
sudo python -m ghpythonremote._configure_ironpython_installation /Users/XXX/Library/Application\ Support/McNeel/Rhinoceros/MacPlugIns/IronPython/settings/lib

MAKE SURE you have "sudo" and "MacPlugIns". I do not know if "MacPlugIns" is important but since there is such a folder... I got the same following issues after installing to
~/Library/Application\ Support/McNeel/Rhinoceros/6.0/Plug-ins/IronPython (814d908a-e25c-493d-97e9-ee3861957f49)/settings/lib

The file GHPythonRemote.ghuser is at its right place:
~/Library/Application\ Support/McNeel/Rhinoceros/MacPlugIns/IronPython/settings/lib/ghpythonremote/ghcluster/GHPythonRemote.ghuser

- I unfortunately get stucked here:
It cannot import ghpythonremote when running "GH_python_remote.ghx" from 
~/Library/Application\ Support/McNeel/Rhinoceros/MacPlugIns/IronPython/settings/lib/ghpythonremote/examples
gives me the error: "No module named ghpythonremote"

I think something _very_ basic related to the paths is wrong. But I cannot figure it out.

I you have an idea... I am almost there, or am I being optimistic ? ;)

**Comment by metacomgd** [comment] 2020-12-01 22:30
I've forked and added initial mac support for Rhino 7.0; not sure if my cahnges will break anythin on windows so no PR yet. 

take a look here https://github.com/metacomgd/ghpythonremote

one caveat, you have to copy the files from ghpythonremote/ghpythonremote  to /Users/XXXX/Library/Application\ Support/McNeel/Rhinoceros/7.0/scripts/ghpythonremote/

i.e.
`git clone https://github.com/metacomgd/ghpythonremote.git`
`cd ghpythonremote/`
`sudo python setup.py install`
`sudo python -m ghpythonremote._configure_ironpython_installation 7`
`sudo cp -r ghpythonremote/ ~/Library/Application\ Support/McNeel/Rhinoceros/7.0/scripts/`

**Comment by crossingchen** [comment] 2021-01-06 06:54
Hi @metacomgd, I tried the mac installation described above and it seems to work. But when I use the pythonremote module in grasshopper, I got an error saying

> Runtime error (ImportException): No module named winreg
>Traceback:
  line 12, in <module>, "/Users/xxxx/Library/Application Support/McNeel/Rhinoceros/7.0/scripts/ghpythonremote/connectors.py"
  line 10, in script

I looked at connectors.py, it is this code that triggers the error
`if platform.system() != 'Darwin':
    try:
        import _winreg as winreg
    except ImportError:
        import winreg`

I'm not very familiar with macOS. Is winreg something for the windows system only? Is there a way to bypass this or have a replacement for mac? Thanks!

**Comment by metacomgd** [comment] 2021-01-06 14:48
Hi @inkmug, 

winreg is something for windows only; the platform.system != Darwin is supposed to skip it if it's not windows; Don't know why it isn't working for you, but you can safely delete that line. For my information, could you paste the result of the following python script from your machine?

import platform
platform.system()

**Comment by crossingchen** [comment] 2021-01-07 05:08
Thank you for your response. I found that the problem is the connectors.py and helpers.py files under folder ghpythonremote/ghpythonremote and /Users/XXXX/Library/Application\ Support/McNeel/Rhinoceros/7.0/scripts/ghpythonremote/ are different. By accident, I was looking at the connectors.py file under ghpythonremote/ghpythonremote, which has the platform.system() check so that I copied in the last post (and my system does return 'Darwin' by the way). 

However the connectors.py and helpers.py files under /Users/XXXX/Library/Application\ Support/McNeel/Rhinoceros/7.0/scripts/ghpythonremote/ do not have any of the platform.system() checks, thus triggers the _winreg line.

I also found there are the lines for Rhino v7 in the helpers.py file under ghpythonremote/ghpythonremote folder. Looks like the files under this folder is more recent.

Not sure why this happens. I used your code above to install the files
`git clone https://github.com/metacomgd/ghpythonremote.git`
`cd ghpythonremote/`
`sudo python setup.py install`
`sudo python -m ghpythonremote._configure_ironpython_installation 7`
`sudo cp -r ghpythonremote/ ~/Library/Application\ Support/McNeel/Rhinoceros/7.0/scripts/`

After I match these files, this issue is gone. But now when I ran the grasshopper PythonRemote component, I got a new error output,
>DEBUG: ghpythonremote.connectors:
>Using python executable: /usr/bin/python
>DEBUG: ghpythonremote.connectors:
>Using rpyc_server module: /Users/xxxx/Library/Application >Support/McNeel/Rhinoceros/7.0/scripts/ghpythonremote/pythonservice.py
>DEBUG: ghpythonremote.connectors:
>Using port: 57563
>DEBUG: ghpythonremote.connectors:
>Using log_level: DEBUG
>DEBUG: ghpythonremote.connectors:
>Using working_dir: /Users/xxxx/Desktop/grasshopper/param_gh
>INFO: ghpythonremote.connectors:
>Connecting...
>DEBUG: ghpythonremote.connectors:
>Connecting. Timeout in 10 seconds.
>DEBUG: ghpythonremote.connectors:
>Connecting. Timeout in 9 seconds.
> Runtime error (RuntimeException): Remote python /usr/bin/python failed on launch. Does the remote python have rpyc installed?
>Traceback:
>  line 168, in _get_connection, "/Users/xxxx/Library/Application Support/McNeel/Rhinoceros/7.0/scripts/ghpythonremote/connectors.py"
>  line 58, in __init__, "/Users/xxxx/Library/Application Support/McNeel/Rhinoceros/7.0/scripts/ghpythonremote/connectors.py"
  line 54, in script

I was not able to install rpyc module for python 2.7. Through conda I got:
>failed
>UnsatisfiableError: The following specifications were found to be incompatible with the existing python installation in your environment:
>Specifications:
>  - rpyc -> python[version='>=3.7,<3.8.0a0']
>Your python: python=2.7

Through pip I got:
>Collecting rpyc
>  Could not fetch URL https://pypi.python.org/simple/rpyc/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
>  Could not find a version that satisfies the requirement rpyc (from versions: )
>No matching distribution found for rpyc

**Comment by crossingchen** [comment] 2021-01-07 06:25
The ssl error was fixed after I updated my pip from 9.0.1 to 9.0.3. So I installed rpyc 4.1.4 for python 2.7. 
I also installed rpyc 4.1.5 in conda using this link, https://anaconda.org/conda-forge/rpyc/files.
But still get the same error in grasshopper, 

> Runtime error (RuntimeException): Remote python /usr/bin/python failed on launch. Does the remote python have rpyc installed?
> 
> Traceback:
>   line 168, in _get_connection, "/Users/xxxx/Library/Application Support/McNeel/Rhinoceros/7.0/scripts/ghpythonremote/connectors.py"
>   line 58, in __init__, "/Users/xxxx/Library/Application Support/McNeel/Rhinoceros/7.0/scripts/ghpythonremote/connectors.py"
>   line 54, in script

**Comment by metacomgd** [comment] 2021-01-07 07:24
iirc there is a path issue; try
`pip install -t ~/Library/Application\ Support/McNeel/Rhinoceros/7.0/scripts/ rpyc plumbum`

**Comment by crossingchen** [comment] 2021-01-08 07:05
Thank you for the response. I still got the same error after this installation. I tried in the terminal directly:
`from ghpythonremote import rpyc`
`connection = rpyc.utils.factory.connect("localhost",50631, service=rpyc.core.service.ClassicService, config={"sync_request_timeout": None}, ipv6=False, keepalive=True)`
and get this error

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rpyc/utils/factory.py", line 98, in connect
>     s = SocketStream.connect(host, port, ipv6=ipv6, keepalive=keepalive)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rpyc/core/stream.py", line 172, in connect
>     return cls(cls._connect(host, port, **kwargs))
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rpyc/core/stream.py", line 124, in _connect
>     s = socket_backoff_connect(family, socktype, proto, sockaddr, timeout, attempts)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rpyc/lib/__init__.py", line 131, in socket_backoff_connect
>     sock.connect(addr)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> socket.error: [Errno 61] Connection refused

Did a bunch of search on this error code but no luck. I can establish python simpleHTTP so not sure what else is causing this.

Similar to this issue
https://www.food4rhino.com/app/gh-python-remote?page=7

**Comment by metacomgd** [comment] 2021-01-08 10:02
@inkmug that is not unexpected; unless you have something istening on port 50631, it will always fail that way; in another terminal run 
`nc -l 50631`
and run the same python snippet again, you should see some data showing up in the 2nd terminal; It is possible that there is some firewall issue and this should help to rue that out.

**Comment by crossingchen** [comment] 2021-01-08 19:23
So this means rpyc is installed fine but for some reason the connection cannot be established? I checked the fire wall and python is listed as "allow incoming connections". And `nc -l 50631` worked with the snippet. 

I read the port number (50631) from grasshopper just to test if rpyc is installed. This number changes every time I toggled on the component. Were you recommending me run the `nc -l port` in a different terminal while using grasshopper? How do I know which port to use? Or the code itself will establish the connection if everything's set up correctly and I'm missing something? Thanks.

**Comment by crossingchen** [comment] 2021-01-17 18:36
I made the following changes and now it works. I'm using Rhino 7 and Catalina 10.15.6.
It looks like I have multiple python2 versions installed on the computer and for the one under /usr/bin/python rpyc was not installed.

1. in /Users/xxxx/Library/Application Support/McNeel/Rhinoceros/7.0/scripts/ghpythonremote/helpers.py
change 
`def get_python_path(location=None):
    if platform.system() == 'Darwin':
        return '/usr/bin/python'`
to
`def get_python_path(location=None):
    if platform.system() == 'Darwin':
        return '/Users/xxxx/anaconda3/envs/py2/bin/python'`
2. in the PythonRemote grasshopper component
change
`ROOT = path.abspath(path.dirname(inspect.getfile(ghpythonremote)))`
`rpyc_server_py = path.join(ROOT, "pythonservice.py")`
to
`root2 = "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gh_python_remote-1.3.1-py2.7.egg/ghpythonremote"`
`rpyc_server_py = path.join(root2, "pythonservice.py")`

**Comment by pilcru** [comment] 2021-01-27 20:05
Fixed in v1.4.0

Thank you to all who contributed in this thread -- I finally made a Mac version of the plugin and all the code you've shown has been very helpful.

@metacomgd, I ended up not going with your fork, as it did not have some of the functionalities I wanted to integrate (mainly, supporting conda envs).

@metacomgd and @inkmug , I see you are using the base MacOS python installation (`/usr/bin/python`) as your remote Python. I think this is a bad idea, as this Python installation is intended for use by the system, not by the user. It sometimes gets overwritten on system updates, and is an outdated version. Instead you should use a separate Python installation, ideally with support for virtual environments. There are many ways to do that on Mac, my personal preference is to use miniconda (https://docs.conda.io/en/latest/miniconda.html), installed using brew (https://formulae.brew.sh/cask/miniconda).

**Closed as completed by pilcru** 2021-01-27 20:05 UTC
Labels: future
