### ISSUE TITLE
MacOS compatibility

### ISSUE THREAD

**Issue by opasquetdotfr** [Digital-Structures/ghpythonremote#36] opened 2020-10-01 12:36 UTC
Hello !

I read this is only compatible for Windows.
Am I right if I say making it work under MacOS is only a question of path syntax in the "helpers.py" ?

Thanks !

**Comment by pilcru** [comment] 2020-10-01 12:57
Yes this only installs under Windows. Supporting MacOS requires adding the relevant paths and error messages in "helpers.py" and "_configure_ironpython_installation.py", working around the Windows Registry reads in "connectors.py", choosing between options intelligently and testing on Windows and MacOS.

I've recently gotten a Mac so I'll be able to do this at some point. Meanwhile, happy to look at any PR sent my way.

**Comment by pilcru** [comment] 2020-10-01 12:58
Duplicate of #17

**Closed as completed by pilcru** 2020-10-01 12:58 UTC
